import json
from typing import Any
from dapr.clients import DaprClient

def as_topic_name(event: Any) -> str:
  # schema prefix allow us to recognize our topics from other topics existing in the same ecosystem
  schema_prefix = "onlexnet:v1"
  # by practice, all events generated by avro has egnerated RECORD_SCHEMA property
  # so that we use them to extract full type name, used by convention as part of topic name
  topic_name = f"{schema_prefix}:{event.RECORD_SCHEMA.fullname}"
  return topic_name

def publish(dc: DaprClient, event: Any):

  topic_name = as_topic_name(event)

  event_as_dict = event.to_avro_writable()
  as_json = json.dumps(event_as_dict)
  dc.publish_event(pubsub_name="pubsub", topic_name=topic_name, data = as_json, data_content_type="application/json", publish_metadata={ "ttlInSeconds": "10" })

