# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"\x0c\n\nTimeClient\"\x0b\n\tClientTag22\n\rTimeScheduler\x12!\n\x04tick\x12\x0b.TimeClient\x1a\n.ClientTag\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TIMECLIENT']._serialized_start=16
  _globals['_TIMECLIENT']._serialized_end=28
  _globals['_CLIENTTAG']._serialized_start=30
  _globals['_CLIENTTAG']._serialized_end=41
  _globals['_TIMESCHEDULER']._serialized_start=43
  _globals['_TIMESCHEDULER']._serialized_end=93
# @@protoc_insertion_point(module_scope)
