# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import schema_pb2 as schema__pb2


class TimeSchedulerStub(object):
    """Each client, interested in 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.tick = channel.unary_unary(
                '/TimeScheduler/tick',
                request_serializer=schema__pb2.TimeClient.SerializeToString,
                response_deserializer=schema__pb2.ClientTag.FromString,
                )


class TimeSchedulerServicer(object):
    """Each client, interested in 
    """

    def tick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeSchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'tick': grpc.unary_unary_rpc_method_handler(
                    servicer.tick,
                    request_deserializer=schema__pb2.TimeClient.FromString,
                    response_serializer=schema__pb2.ClientTag.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TimeScheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TimeScheduler(object):
    """Each client, interested in 
    """

    @staticmethod
    def tick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TimeScheduler/tick',
            schema__pb2.TimeClient.SerializeToString,
            schema__pb2.ClientTag.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
